import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { ToastContainer } from "react-toastify";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${inter.className} bg-[#393646]`}>
          <Navbar />
          {children}
          <ToastContainer />
        </body>
      </Providers>
    </html>
  );
}
